version: "3.8"
services:
  postgres:
    container_name: fastapi-postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
  redis:
    container_name: fastapi-redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
